name: backend-ci
on: [push, pull_request]
jobs:
build-test:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- uses: actions/setup-dotnet@v4
with:
dotnet-version: '8.0.x'
- name: Restore
run: dotnet restore backend/Sherine.Api/Sherine.Api.csproj
- name: Build
run: dotnet build backend/Sherine.Api/Sherine.Api.csproj -c Release --no-restore
- name: Test
run: dotnet test backend/Sherine.Tests/Sherine.Tests.csproj --collect:"XPlat Code Coverage"