# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - sherinetravels-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          mkdir -p build_output
          cp -r .next/standalone/* build_output/
          mkdir -p build_output/.next
          cp -r .next/static build_output/.next/
          if [ -d "public" ]; then cp -r public build_output/public; fi
          cp package.json build_output/
        working-directory: ./frontend/web

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./frontend/web/build_output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./frontend/web/build_output
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8FBB5ED0D0394CFCB6AC1898B222BD7D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C847DE4F6136468F91E4DDFE2A493C27 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A249DF3EC2E24CC7A4728AB74D7F3899 }}

      - name: Wait for SCM to stabilize
        run: sleep 20

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sherinetravels-web'
          slot-name: 'Production'
          package: ./frontend/web/build_output
          startup-command: 'node server.js'

          
