name: Build and Deploy Next.js Frontend to Azure

on:
  push:
    branches:
      - main   # change if your frontend branch is different
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/web/package-lock.json'

      - name: Verify package-lock.json exists
        working-directory: ./frontend/web
        run: |
          ls -la package-lock.json
          echo "Package-lock.json found, proceeding with npm ci"
      
      - name: Install dependencies
        working-directory: ./frontend/web
        run: npm ci

      - name: Build Next.js app
        working-directory: ./frontend/web
        run: npm run build

      - name: Prepare deployment package
        working-directory: ./frontend/web
        run: |
          mkdir -p ../deploy
          cp -r .next package.json public ../deploy
          [ -f next.config.mjs ] && cp next.config.mjs ../deploy || true
          [ -f next.config.js ] && cp next.config.js ../deploy || true
          cd ../deploy
          zip -r ../webapp.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sherinetravels-web'
          slot-name: 'Production'
          package: ./frontend/deploy/webapp.zip
